import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Footer from "./components/footer";
import Header from "./components/header";
import generalDataJson from "./data/general.json";
import { getGeneralData } from "./lib/data";

// fonts
const Gotham = localFont({
	src: [
		{
			path: "../public/fonts/Gotham-Light.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "../public/fonts/Gotham-Book.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/Gotham-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/GothamBold.woff2",
			weight: "700",
			style: "normal",
		},
	],
});

// Meta data
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


// RootLayout component
export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	console.log("layout component rendered!");

	let { Privacy_Title, Privacy_URL } = await getGeneralData();


	return (
		<html lang="en" className={`${Gotham.className}`}>
			<body className={`${Gotham.className} antialiased`}>
				<Header
					privacyTitle={Privacy_Title}
					privacyUrl={Privacy_URL}
					headerCta={generalDataJson?.headerCta}
					logoUrl={generalDataJson?.logoUrl}
					headerNavigation={generalDataJson?.headerNavigation}
				/>
				{children}
				<Footer
					logoUrl={generalDataJson?.logoUrl}
					footerDescription={generalDataJson?.footerDescription}
					footerNavigation={generalDataJson?.footerNavigation}
					getInTouch={generalDataJson?.getInTouch}
					footerCta={generalDataJson?.footerCta}
				/>
			</body>
		</html>
	);
}

