import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Footer from "./components/footer";
import Header from "./components/header";
import generalDataJson from "./data/general.json";
import { getGeneralData } from "./lib/data";

// fonts
const Gotham = localFont({
	src: [
		{
			path: "../public/fonts/Gotham-Light.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "../public/fonts/Gotham-Book.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/Gotham-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/GothamBold.woff2",
			weight: "700",
			style: "normal",
		},
	],
});

// Meta data
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// RootLayout component
export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	console.log("layout component rendered!");

	// Fetch general data
	let generalData = await getGeneralData("populate=*"),
		footerData = await getGeneralData("populate[Footer_Navigation][populate][0]=Important_Links&populate[Get_In_Touch][populate][0]=Emails&populate[Footer_Cta][populate][0]=Footer_Links_Urls");
		
	generalData = { ...generalData, ...footerData };



	// console.log("General Data from Strapi:", generalData);

	const privacy__title = generalData?.Privacy_Title;
	const privacy__url = generalData?.Privacy_URL;
	const header__cta = generalData?.Header_CTA;
	const logo = generalData?.logo?.url;
	const header__Navigation = generalData?.Header_Navigation;
	const footer__description = generalData?.Footer_Description;
	const footer__Navigation = generalData?.Footer_Navigation;
	const get_in_touch = generalData?.Get_In_Touch;
	const footer_cta = generalData?.Footer_Cta;


	return (
		<html lang="en" className={`${Gotham.className}`}>
			<body className={`${Gotham.className} antialiased`}>
				<Header
					privacyTitle={privacy__title}
					privacyUrl={privacy__url}
					headerCta={header__cta}
					logoUrl={logo}
					headerNavigation={header__Navigation}
				/>
				{children}
				<Footer
					logoUrl={logo}
					footerDescription={footer__description}
					footerNavigation={footer__Navigation}
					getInTouch={get_in_touch}
					footerCta={footer_cta}
				/>
			</body>
		</html>
	);
}

