import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";


// fonts
const Gotham = localFont({
	src: [
		{
			path: "../public/fonts/Gotham-Light.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "../public/fonts/Gotham-Book.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/Gotham-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/GothamBold.woff2",
			weight: "700",
			style: "normal",
		},
	],
});


// Meta data
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${Gotham.className}` }>
			<body className={`${Gotham.className } antialiased`}>{children}</body>
		</html>
	);
}

